# Generated by Django 2.1.7 on 2019-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('short_description', models.TextField(verbose_name='Краткое описание новости')),
                ('description', models.TextField(verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='images/news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'posts',
            },
        ),
    ]
